// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" href=\"/static/water.css\"><script src=\"/static/htmx.min.js\" crossorigin=\"anonymous\"></script><style>\n            .box {\n  border: 2px solid rgba(0,0,0,0.25);\n  padding: 1rem;\n  margin: 1rem 0;\n}\n\n            .box ul, .box ol {\n  margin: 1em 0;\n  padding-left: 2em;\n            }\n\n            .box ul {\n  list-style-type: disc;\n            }\n\n            .box ol {\n  list-style-type: decimal;\n            }\n\n            .box li {\n  margin: 0.5em 0;\n            }\n\n            </style><script>\n            function autoResizeTextarea(ta) {\n                ta.style.height = 'auto';\n                ta.style.height = ta.scrollHeight + 'px';\n            }\n            document.addEventListener('DOMContentLoaded', function() {\n                document.querySelectorAll('textarea').forEach(autoResizeTextarea);\n                document.body.addEventListener('htmx:afterSwap', function() {\n                    document.querySelectorAll('textarea').forEach(autoResizeTextarea);\n                });\n            });\n            </script></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
